### ISSUE TITLE
[FEATURE-REQUEST] Guardian integration

### ISSUE THREAD

**Issue by joshuaswilcox** [aesmail/kaffy#109]
**Describe the problem you're proposing to solve**
I would like to integrate with guardian authentication

**Describe the solution you'd like**
I would like to provide a pipeline that the controllers use for authentication like
    
      pipeline :auth do
        plug MyApp.Auth.AuthAccessPipeline
        plug MyAppWeb.Context
     end
    use Kaffy.Routes, scope: "/admin", pipe_through: [:browser, :auth

while having the controllers use this auth like
   
      import MyApp.Auth, only: [load_current_user: 2]
     plug(:load_current_user)

**Describe alternatives you've considered**
basic_auth on the browser with nginx

**Comment by aesmail** [comment]
Would [loading the resource](https://hexdocs.pm/guardian/Guardian.Plug.LoadResource.html#content) in the pipeline solve this issue?

**Comment by aesmail** [comment]
Will close this for now. Please let me know if you're still having issues with this.

**Comment by joshuaswilcox** [comment]
So i do load that in the `MyApp.Auth.AuthAccessPipeline` class

    defmodule MyApp.Auth.AuthAccessPipeline do
      @moduledoc false

      use Guardian.Plug.Pipeline, otp_app: :scotchy_api

      plug(Guardian.Plug.VerifySession, claims: %{"typ" => "access"})
      plug(Guardian.Plug.EnsureAuthenticated)
      plug(Guardian.Plug.LoadResource)
    end

But i believe the issue is still in the controllers actually using the `load_current_user` method to read the session

**Comment by aesmail** [comment]
Yes. This will actually load the user (or whatever resource you're using with guardian) from the session.
You'd be able to access it from `conn.private` I believe.
Something like `conn.private[:guardian_default_resource]` I think. You can `IO.inspect(conn.private)` to see the exact name `guardian` is using to store the resource.
