### ISSUE TITLE
[FEATURE-REQUEST] Ability to show media types

### ISSUE THREAD

**Issue by antonioparisi** [aesmail/kaffy#113]
**Describe the problem you're proposing to solve**
Ability to show media (images, videos) on a index page as a new column type.

**Comment by areski** [comment]
Hi @antonioparisi 
The support for this has been recently added, see https://github.com/aesmail/kaffy/issues/54

**Comment by antonioparisi** [comment]
ah that's awesome. 👍 also I noticed it's not been released just yet since 0.8.1 has not got it - I guess it's gonna be part of the 0.9 milestone
