### ISSUE TITLE
Live Demo not saving json content?

### ISSUE THREAD

**Issue by WernerBuchert** [aesmail/kaffy#114]
Hi,

I' wondering how to edit json-content in the live-Demo:

https://kaffy.gigalixirapp.com/admin/products/product/1

with option:

{
  "calories": 348,
  "sugar": 18
}
is always saying "options is invalid".

The strange thing is, that this is just the value for option, that is, i changed nothing.

Thanks,
Werner.

**Comment by aesmail** [comment]
Hello @WernerBuchert 
Good catch!
