### ISSUE TITLE
[BUG] The :method option is not applied on custom-links

### ISSUE THREAD

**Issue by nresni** [aesmail/kaffy#126]
**Versions Used**
Kaffy: 0.8.1
Phoenix: 1.5.3
Elixir: 1.10.3

**What's actually happening?**
The `:method` option is not applied in custom-links. All links are in `GET` even if you set `DELETE`.

**What should happen instead?**
Use the specified `:method`

**Comment by aesmail** [comment]
PR merged, thanks!
