### ISSUE TITLE
[FEATURE-REQUEST] Allow searching by id

### ISSUE THREAD

**Issue by tensiondriven** [aesmail/kaffy#134]
**Describe the problem you're proposing to solve**

A common use case for an admin panel is to look up a record by id.  I can add `:id` by implementing `search_fields()`, but according to https://github.com/aesmail/kaffy#search only string fields are supported.

**Describe the solution you'd like**
Support searching on numeric fields in addition to `:string` / `:text`.

**Describe alternatives you've considered**

Typing the id into the URL (assuming the resource id is the id i want)

**Additional context**

This is a brilliant piece of work and much needed in the Elixir/Phoenix community... and finally done right.  Already useful, and, can't wait till its more fleshed out.

**Comment by aesmail** [comment]
I actually needed this today, a lot. It's safe to assume this is coming in the next minor release.
