### ISSUE TITLE
[BUG] Allow custom Ecto.Type for string type

### ISSUE THREAD

**Issue by eaguilera23** [aesmail/kaffy#136]
**Versions Used**
Kaffy: 0.9.1
Phoenix: 1.5.1
Elixir: 1.10.4

**What's actually happening?**
* I have a Schema with a custom `Ecto.Type` which is `def type, do: :string`.
* If I open the "Create" page of this schema it throws `argument error` on 

```
(kaffy 0.9.1) lib/kaffy/resource_form.ex:305: Kaffy.ResourceForm.text_or_assoc/5
```

**Disclaimer**
Besides that one, I didn't have any other `string` field. So I don't know if that's the real problem.

**What should happen instead?**
It recognises it as a custom type, with `:string` underneath.

**Screenshots**
<img width="1023" alt="Screen Shot 2020-07-25 at 1 53 05 PM" src="https://user-images.githubusercontent.com/40353069/88455465-2cbce700-ce7e-11ea-8310-9aa01fb8c07a.png">

**Comment by aesmail** [comment]
fixed with #137
