### ISSUE TITLE
[BUG] Using Posgres Enum crash kaffy

### ISSUE THREAD

**Issue by Rachc** [aesmail/kaffy#138]
**Versions Used**
Kaffy: 0.9.0
Phoenix: 1.5.0
Elixir: 1.10

**What's actually happening?**
When we use Postgres Enum in our schema, it crashes when we try to see the list of the elements on Kaffy interface.

Here is a short snippet of our schema
```elixir
defmodule MyApp.School do
  use Ecto.Schema
  import Ecto.Changeset

  schema "schools" do
    (...)
    field :status, :string
    (...)
  end

  def changeset(school, attrs) do
    school
    (...)
    |> validate_inclusion(:status, ["active", "inactive"])
end
```
and our migration
```elixir
def up do
    execute "create type school_status as enum ('active', 'inactive')"

    create table(:schools, primary_key: false) do
      (...)
      add :status, :school_status, null: false
    end
end
```
We found that if you try to use `status::text like '%%'` on your query instead `status like '%%'` it should work.

We tried to use custom query to solve this problem but there is a bypass of the original query and we can't use our query.

Here is a snipet of the code we suspsect are causing this issue (module `Kaffy.ResourceQuery`, lines 17 to 33)
```elixir
{all, paged} =
      build_query(
        schema,
        search_fields,
        filtered_fields,
        search,
        per_page,
        ordering,
        current_offset
      )

    custom_query = Kaffy.ResourceAdmin.custom_index_query(conn, resource, paged)
    current_page = Kaffy.Utils.repo().all(custom_query)

    do_cache = if search == "" and Enum.empty?(filtered_fields), do: true, else: false
    all_count = cached_total_count(schema, do_cache, all)
    {all_count, current_page}
```

**What should happen instead?**
It should list all the elements that has enum on posgresql

**Screenshots**
![image](https://user-images.githubusercontent.com/1789745/88834058-a409b800-d1a9-11ea-9453-cbd8a4bdf731.png)

**Comment by brosquinha** [comment]
A possible solution to this problem may be to cast all fields as string in order to perform `ilike` operation, like [so](https://github.com/aesmail/kaffy/compare/master...brosquinha:fix/enum-ilike)

**Comment by aesmail** [comment]
Thank you @Rachc for the detailed report. I really appreciate it.

@brosquinha this could work! Thanks.

I expect this to be fixed with v0.9.1 which should be released in a few days.

**Comment by brosquinha** [comment]
> Thank you @Rachc for the detailed report. I really appreciate it.
> 
> @brosquinha this could work! Thanks.
> 
> I expect this to be fixed with v0.9.1 which should be released in a few days.

Should I open a PR with these changes?

**Comment by aesmail** [comment]
Feel free to tackle this. But one thing to keep in mind is that v0.9.1 should also fix #134 which allows searching numeric fields as well.

**Comment by aesmail** [comment]
@brosquinha on second thought, its' fine to submit a PR specifically for this issue since there's already partial work done for #134. We'll try to combine the two solutions later on.

**Comment by aesmail** [comment]
#139 closes this one
