### ISSUE TITLE
Add very simple dashboard customizations

### ISSUE THREAD

**Issue by aesmail** [aesmail/kaffy#14]

**Comment by eaguilera23** [comment]
Are you planning on adding kind of metrics? Graphs, etc...?

**Comment by aesmail** [comment]
The idea is to have textual widgets and some very simple graph widgets. Currently I have an early prototype of how this is going to work. I think it will be a great addition to kaffy.
Do you have a specific need?

**Comment by aesmail** [comment]
This is done and released in v0.5.0
This will be improved in later versions, but the basis is there.
