### ISSUE TITLE
Demo unavailable

### ISSUE THREAD

**Issue by xire28** [aesmail/kaffy#143]
Reproduction: Access demo link (https://kaffy.gigalixirapp.com/admin/)

Error message:
```
Sorry, looks like your app is not running. Try scaling up by running `gigalixir ps:scale --replicas=1` 
```

**Comment by reneweteling** [comment]
Hey guys, where do you have the source code for the demo? ill be happy to through it one of my servers?

**Comment by aesmail** [comment]
Hey @reneweteling 
Thanks for the initiative!
The source code is available here https://github.com/aesmail/kaffy-demo
I was away from kaffy for a few weeks and I just started spending more time on kaffy and was about to get the demo back up online.

**Comment by godbrain** [comment]
I was worried about this and hoping it wasn't another cool project that was not going to be maintained.  Thanks

**Comment by Marciola** [comment]
Just wanted to add, the demo still doesn't seem to be up
