### ISSUE TITLE
[BUG] froms do not save when I provide custom resources

### ISSUE THREAD

**Issue by cultofmetatron** [aesmail/kaffy#152]
**Versions Used**
Kaffy: 0.9.0
Phoenix: 1.5.4
Elixir: 1.10.4

**What's actually happening?**
I added some configuration

```elixir
config :kaffy,
  otp_app: :tellebee_admin,
  ecto_repo: TellebeeAdmin.Repo,
  router: TellebeeAdminWeb.Router,
  resources: &TellebeeAdminWeb.Kaffy.Config.create_resources/1

```

and heres' the file

```elixir
defmodule TellebeeAdminWeb.Kaffy.Config do

  alias TellebeeAdmin.DB.{Child, User, UserAdmin}

  def create_resources(_conn) do
    [
      main: [
        name: "Main", # a custom name for this context/section.
        schema: ["users", "children"],
        resources: [ # this line used to be "schemas" in pre v0.9
          users: [schema: User, admin: UserAdmin],
          children: [schema: Child, title: "children"],
        ]
      ]
    ]
  end
end

```

Now when I go into the admin panel, I am unable to create a new user. it errors. if I remove the configurations and rely on the default, it works but when I hook this back in, it returns that the save is successful but the record is not saved. I can see in the console that the app does not even attempt an insert.

I added an io and cutom insert changesets

```elixir
defmodule TellebeeAdmin.DB.UserAdmin do

  alias TellebeeAdmin.DB.User

  def form_fields(_) do
    [
      email: %{type: :text},
      active: %{type: :boolean},
      password: %{type: :password}
    ]
  end

  def create_changeset(schema, attrs) do
    # do whatever you want, must return a changeset
    IO.inspect("inserting!!")
    User.changeset(schema, attrs)
  end

  def update_changeset(entry, attrs) do
    # do whatever you want, must return a changeset
    IO.inspect(("updateing"))
    User.changeset(entry, attrs)
  end

end

```

the updating log does show up in the console so whatever is happening is after this callback is run. 

**What should happen instead?**

The save form should work

**Comment by aesmail** [comment]
Hey @cultofmetatron 

The keys in the keyword list returned by your `create_resources/1` function must resemble your contexts and schemas.

The following means you have a `main` context which has `User` and `Children` schema modules. See the inline comments in the following snippet:

```elixir
def create_resources(_conn) do
    [
      main: [ # <- the context "name" as an atom
        name: "Main",
        schema: ["users", "children"],
        resources: [
          users: [schema: User, admin: UserAdmin], # <- users should be user
          children: [schema: Child, title: "children"], # <- children should be child
        ]
      ]
    ]
end
```

Let me know if this doesn't work.

**Comment by cultofmetatron** [comment]
thankyou! that fixed it!
