### ISSUE TITLE
[BUG] Cannot render the dashboard

### ISSUE THREAD

**Issue by introvert** [aesmail/kaffy#153]
First of all, thank you for the initiative to creative the missing admin for Phoenix!

**Versions Used**
Kaffy: 0.9.0
Phoenix: v1.5.4
Elixir: 

**What's actually happening?**
When I try to access /admin, I get the following error:
`function MyApp.Router.Helpers.kaffy_dashboard_path/2 is undefined (module MyApp.Router.Helpers is not available)`

Here's my config:
```
config :kaffy,
  otp_app: :myapp,
  # admin_title: "My Awesome App",
  # admin_logo: "/images/logo.png",
  # admin_logo_mini: "/images/logo-mini.png",
  hide_dashboard: true,
  home_page: [kaffy: :dashboard],
  ecto_repo: Cointracker.Repo,
  router: Cointracker.Router
```

What is the reason that helper function is not available? Am I missing something?

Thank you

**Comment by aesmail** [comment]
Your router module might be CointrackerWeb.Router instead of Cointracker.Router if you're using default Phoenix naming conventions.

**Comment by aesmail** [comment]
Hey @introvert 
Did this fix your issue?

**Comment by oivoodoo** [comment]
Hi @aesmail . it is definitely the fix. I had the same mis configuration. now it's working great. thank you!
