### ISSUE TITLE
New view for records with many_to_many relation bails

### ISSUE THREAD

**Issue by bumbus** [aesmail/kaffy#168]
**Versions Used**
Kaffy: 0.9.0
Phoenix: 1.5.4
Elixir: 1.9.1

**What's actually happening?**
I have a schema with a many_to_many relation, joining though an other schema, like this:

```
schema "participants_groups" do
    field(:name, :string)
    many_to_many(:players, Participants.Player,
      join_through: Participants.GroupPlayer
    )
  end
```
But it raises the following:

```
protocol Phoenix.HTML.Safe not implemented for #Ecto.Association.NotLoaded<association :players is not loaded> of type Ecto.Association.NotLoaded (a struct). ...
```

**What should happen instead?**

Yeah, guess what it should render the form :)

**Comment by Qizot** [comment]
From what I understand `many_to_many` relations are not supported yet.

**Comment by bumbus** [comment]
Looks, like, but is there a way to somehow deactivate this data field? I tried several ways like in the according admin module:

```  def form_fields(_) do
    [
      name: nil,
      players: nil
    ]
  end

But no luck.

**Comment by Qizot** [comment]
Just simply don't put the `players` field inside the list and it should work.

**Comment by bumbus** [comment]
true that, thank you for helping out
