### ISSUE TITLE
[BUG] admin_logo and admin_mini_logo configuration not implemented

### ISSUE THREAD

**Issue by manuel-rubio** [aesmail/kaffy#175]
**Versions Used**
Kaffy: 0.9.0
Phoenix: 1.5.4
Elixir: 1.10.4

**What's actually happening?**
I configure the `admin_logo` and `admin_mini_logo` images but it doesn't work. I checked the code and I can see it's not implemented indeed.

**What should happen instead?**
Use a custom logo instead of the usual kaffy logo.

**Comment by MartinElvar** [comment]
Hello @manuel-rubio, 

This is yet to be rolled out, will be out with the next release.

**Comment by manuel-rubio** [comment]
thanks @MartinElvar
