### ISSUE TITLE
[BUG] Kaffy incorrectly handles the type `{:array, :string}` for PostgreSQL

### ISSUE THREAD

**Issue by yonkeltron** [aesmail/kaffy#184]
**Versions Used**
Kaffy: 0.9.0
Phoenix: 1.5.7
Elixir: 1.11

**What's actually happening?**
The column is rendered as a text field with all elements in the array concatenated together. If they array is `["P", "Q", "R"]` then the text field has the value of "PQR" and the record cannot be saved or updated as those fields cause validation errors.

**What should happen instead?**
If there is no possibility of a multi-select or a series of option boxes, the text field should render and accept comma-separated values.

**Screenshots**
No screenshots here.

**Additional notes**
Please do not hesitate to reach out with additional questions or if I can help test anything. I really appreciate the immense effort shown on this project and look forward to using it even more.

**Comment by Stefano1990** [comment]
I guess this is related to #130

**Comment by kelcecil** [comment]
Hey there! I’ve merged a potential bug fix for this issue. If you’re still using kaffy and running into this issue, I’d appreciate if you’d try running against master and seeing if you still have the issue. Thanks!

**Comment by aesmail** [comment]
I can confirm that master displays and updates `{:array, :string}` fields correctly.
