### ISSUE TITLE
[BUG] module Kaffy.Routes is not loaded and could not be found

### ISSUE THREAD

**Issue by kmacdough** [aesmail/kaffy#191]
**Versions Used**
Kaffy: 0.9.0
Phoenix: 1.5.7
Elixir: 1.11.2

**What's actually happening?**
When I run `mix phx.server` I get:
```
** (CompileError) lib/<my_site_name>_web/router.ex:4: module Kaffy.Routes is not loaded and could not be found
```

I believe I followed the install instructions to the letter.

1) The first 3 lines of my `routes.ex`
```
defmodule <MySiteName>Web.Router do
  use <MySiteName>Web, :router
  use Kaffy.Routes, scope: "/admin", pipe_through: []
```
2) In my `config.exs` file between the autogenerated <MySiteName>Web.Endpoint & logger configs. 
```
config :kaffy,
  otp_app: :scuba_site,
  ecto_repo: <MySiteName>.Repo,
  router: <MySiteName>Web.Router
```
3) In my `endpoint.ex` file after the autogenerated `Plug.Static` plug:
```
  plug Plug.Static,
    at: "/kaffy",
    from: :kaffy,
    gzip: false,
    only: ~w(assets)
 ```
 4) I also ran `mix deps.get` and `mix deps.compile` separately with no errors. Not included in the Kaffy install instructions.

**What should happen instead?**
I would imagine following the "Minimal Install Instructions" would at least result in a functional app that runs with `mix phx.server`. Presumably the minimal instructions would also result in at least one admin page, but we're not there yet.

**Screenshots**

**Comment by kmacdough** [comment]
Sorry! Turns out it was a newbie mistake (imagine that); removing _build/ and deps/ and reinstalling worked great. I can only guess that something threw of `deps.get`. Amazing package 👍

**Comment by aesmail** [comment]
Hey @kmacdough, apologies for not replying sooner.
Glad it worked out for you 🙏🏼
Let me know if you face any more problems down the road.
