### ISSUE TITLE
[BUG] Select all checkbox sends a blank string as an ID and causes an error

### ISSUE THREAD

**Issue by yonkeltron** [aesmail/kaffy#198]
**Versions Used**
Kaffy: `0.9.0` as per the latest on hex.pm
Phoenix: `1.5.7`
Elixir: 1.11.3

More Elixir/Erlang info:

```bash
$ elixir --version
Erlang/OTP 23 [erts-11.1.7] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.11.3 (compiled with Erlang/OTP 23)
```

**What's actually happening?**

When selecting all using the checkbox at the far left of the table heading in list views, it has a blank value but is still part of the form. Ergo, performing a list action, say on one other record, sends an ID list of `["", "1"]` which causes an Ecto cast error:

```
Ecto.Query.CastError at POST /admin/request/role/action/approve

deps/kaffy/lib/kaffy/resource_query.ex:59: value `["", "1"]` in `where` cannot be cast to type {:in, :id} in query:
...snip...
```

**What should happen instead?**

The select-all checkbox should either

1. Not be part of the submitted form so that it doesn't submit an empty string in the first place
1. The empty string should be filtered out before resources are loaded in Kaffy's `resource_controller.ex`

**Additional environmental info**

This problem can be reproduced on macOS 10.14.6 with the following settings:

```bash
$ uname -a                                                                                                           10:52:06
Darwin HOSTNAME.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Nov 10 00:07:31 PST 2020; root:xnu-4903.278.51~1/RELEASE_X86_64 x86_64
```

**Comment by hannah-reed** [comment]
PR #192 to add Enum support will resolve this issue

**Comment by yonkeltron** [comment]
Can confirm this is still an issue, but it does look like @hannah-reed made an accurate comment! Thanks for pointing out PR #192, great call out.

**Comment by kelcecil** [comment]
Hi there! #192 was just merged to master. Could someone confirm if the bug is still present on the master branch? Thanks!
