### ISSUE TITLE
Ability to have custom filters on the index resource pages

### ISSUE THREAD

**Issue by antonioparisi** [aesmail/kaffy#20]
@aesmail coming from react-admin I found custom filters very useful

would be nice to have something like this:
<img width="1030" alt="Screenshot 2020-05-13 at 15 27 28" src="https://user-images.githubusercontent.com/1324178/81825209-43fe6080-952e-11ea-927f-cf420c66dde5.png">

<img width="1215" alt="Screenshot 2020-05-13 at 16 20 35" src="https://user-images.githubusercontent.com/1324178/81831780-aeff6580-9535-11ea-885c-6e7ae1fdd311.png">

**Comment by aesmail** [comment]
This is *definitely* a must-have. Thank you.
Expect it in the next release.

**Comment by aesmail** [comment]
This is done and released in v0.4.1.
Please check [customizing the index page](https://github.com/aesmail/kaffy#index-page) section in the README file.
