### ISSUE TITLE
Kaffy try to save strings instead of atoms[BUG]

### ISSUE THREAD

**Issue by palmo25** [aesmail/kaffy#204]
**Versions Used**
Kaffy: 0.9.0
Phoenix:  1.5.7
Elixir: 1.7

**What's actually happening?**
My user has an email and a password field. 
When I try to save a new user account I get this error message "field names given to change/put_change must be atoms, got: `"email"`"

**What should happen instead?**

**Screenshots**

**Comment by blutack** [comment]
If anyone else comes across this, it's fixed in master (at least in cf35712).

Change your mix dep to:

``` {:kaffy, github: "aesmail/kaffy", ref: "cf35712"}```
