### ISSUE TITLE
[FEATURE-REQUEST] Is it possible to show extra fields on `show` forms?

### ISSUE THREAD

**Issue by sardaukar** [aesmail/kaffy#210]
**Describe the problem you're proposing to solve**

I'd like to show extra (computed) info about a record when showing / editing it?

**Describe the solution you'd like**

Ideally, it would be possible to set `value: fn e -> get_info_for(e) end` in `form_fields` for an extra key that is not part of the record's schema.

**Describe alternatives you've considered**

I've considered using `build_choices` to show a dropdown with info, but there's no access to the current record in `form_fields` that I'm aware of.

**Additional context**

I'm using Kaffy for a billing system, and for a given team I'd like to show what features are available for a specific team when showing it. This info is computed from a team's ID.

Let me know if you need more context, and thanks for Kaffy - it's really easy to use!

**Comment by aesmail** [comment]
@sardaukar this would be a nice addition to Kaffy. However, wouldn't adding a virtual field to the schema solve this issue for you? If not, can you please explain why it wouldn't so we have a greater understanding of the problem?
Thanks!

**Comment by sardaukar** [comment]
It's been a while, and I don't use kaffy now so not sure of what my original intent here was. Closing it

**Comment by bitboxer** [comment]
This might be interesting for me. I have a use case where I would love to show data for admins that is computed for that particular element. Using virtual fields would be nice, or as @sardaukar mentioned, a value option on the field itself. I found no good way of initializing the virtual field when editing an entry. If there is one, can you clarify here?

Thanks 🤗
