### ISSUE TITLE
[FEATURE-REQUEST] - compatibility with Phoenix 1.6

### ISSUE THREAD

**Issue by jononomo** [aesmail/kaffy#217]
**Describe the problem you're proposing to solve**

I'm using Phoenix 1.6 and I get this error:
```
Resolving Hex dependencies...

Failed to use "phoenix_html" (version 3.0.3) because
  kaffy (version 0.9.0) requires ~> 2.11
  phoenix_ecto (version 4.4.0) requires ~> 2.14.2 or ~> 3.0
  phoenix_live_view (version 0.16.3) requires ~> 3.0
  mix.lock specifies 3.0.3

** (Mix) Hex dependency resolution failed, change the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock). If you are unable to resolve the conflicts you can try overriding with {:dependency, "~> 1.0", override: true}
```

**Comment by colindensem** [comment]
Same issue exists on 1.5.11 as the ecto version is pushing it up.

**Comment by msp** [comment]
Yep, I ran the fork in #215 happily in 1.5 and now 1.6 RC1 without issue.

**Comment by ilourt** [comment]
Any news to when it will be merged?

Thanks by advance.

**Comment by kelcecil** [comment]
Just merged this today. Would someone mind trying their Phoenix 1.6 setup with master to see if they run into any issues? Would like to get some external confirmation that everything looks good. Thanks!

**Comment by drobban** [comment]
> Just merged this today. Would someone mind trying their Phoenix 1.6 setup with master to see if they run into any issues? Would like to get some external confirmation that everything looks good. Thanks!

Could do that tomorrow morning local sweden time ;)

**Comment by ilourt** [comment]
Thank you very much 😃

**Comment by Nicolab** [comment]
Thank you! :+1:

**Comment by drobban** [comment]
Installed "kaffy": {:git, "git@github.com:aesmail/kaffy.git", "43178b83088e22277fa90456ccc0b9df8cdb0cc0", [ref: "43178b83088e22277fa90456ccc0b9df8cdb0cc0"]},

Kaffy.Utils.phoenix_version?("1.6")
true

And it seems to work fine.
Got one issue, and I got that in the fork from git: "git@github.com:teamwalnut/kaffy.git", ref: "2934d96b3c414256c1add6f6ab22de63b0abff0b"} as well. 
That is when I restart the phx dev server while viewing a specific model I will encounter a :   * 1st argument: invalid UTF8 encoding error. If I then just walk back to path root of kaffy and then get back to the same model, everything works just fine. Not sure if this is a new or old issue.

**Comment by kelcecil** [comment]
Thanks for checking that out. It looks good on my project, but I just wanted to get an additional confirmation.

Would you mind filing a bug report for that issue? I’m not sure that’s it’s a new or old issue either, but we’ll see what we can deduce.

**Comment by aesmail** [comment]
@drobban I think the encoding error due to the way how Kaffy “figures out” your schemas automatically and “loads” them. I’m not sure if it’s consistent and whether it happens every time, but visiting the Kaffy root path will cause it to inspect and load all schemas which then uses this info to display the schema details pages.

I could be a bit off here but I think this is what’s causing it.

I agree with @kelcecil that we should create a new issue for it.

**Comment by drobban** [comment]
> @drobban I think the encoding error due to the way how Kaffy “figures out” your schemas automatically and “loads” them. I’m not sure if it’s consistent and whether it happens every time, but visiting the Kaffy root path will cause it to inspect and load all schemas which then uses this info to display the schema details pages.
> 
> I could be a bit off here but I think this is what’s causing it.
> 
> I agree with @kelcecil that we should create a new issue for it.

sounds like a reasonable explanation.

**Comment by aselder** [comment]
Any news on when 0.9.1 can be released? The phoenix_ecto problem is a huge blocker for me and it looks like lots of others.

Thanks!

**Comment by dottorblaster** [comment]
Huge plus one on this, I'm deeply sorry not to be able to help further but 0.9.1 is truly needed :sweat_smile:

**Comment by arturictus** [comment]
Hi all,
I updated to phx 1.6.6 at #227 and everything works fine.

**Comment by christhekeele** [comment]
#227 is working for me. Is there any news on a v`0.9.1` release, or something that can be done to help it get out the door?

**Comment by luka-TU** [comment]
Hi! Is there a way for me to help with maintaining this project? It looks awesome and it would be a great loss if it is discontinued.

**Comment by aesmail** [comment]
> #227 is working for me. Is there any news on a v`0.9.1` release, or something that can be done to help it get out the door?

@christhekeele a new v0.10 will be released relatively soon (around mid-June).


@luka-TU thank you for the initiative. Kaffy isn't going anywhere 😄. I might need a lot of help after the next release is out. ありがとうございます。

**Comment by luka-TU** [comment]
@aesmail great to hear that! looking forward to the release in that case :)
and would be happy to be of any help with this awesome project 👍 

v0.10.0のリリースをお楽しみにしています！

**Comment by osluf** [comment]
Here's what I added in my `mix.exs` for the time being:

```
{:kaffy, git: "https://github.com/aesmail/kaffy/", ref: "43178b83088e22277fa90456ccc0b9df8cdb0cc0"}
```
