### ISSUE TITLE
[BUG] * 1st argument: invalid UTF8 encoding error on phoenix reboot

### ISSUE THREAD

**Issue by drobban** [aesmail/kaffy#222]
**Versions Used**
Kaffy:  sha: 43178b83088e22277fa90456ccc0b9df8cdb0cc0
Phoenix: 1.6.2
Elixir: 
Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]
Elixir 1.12.2 (compiled with Erlang/OTP 22)

While viewing model all rows is shown as they should. When phx.server is restarted and then page refreshed the following error is shown. The error is consistent behaves the same no matter what "model/schema" I'm viewing rows from and on every reboot of mix phx.server

[error] #PID<0.686.0> running DogGoalWeb.Endpoint (connection #PID<0.629.0>, stream id 22) terminated
Server: localhost:4000 (http)
Request: GET /admin/accounts/user
** (exit) an exception was raised:
    ** (ArgumentError) errors were found at the given arguments:

  * 1st argument: invalid UTF8 encoding

        :erlang.binary_to_existing_atom("accounts", :utf8)
        (kaffy 0.9.1) lib/kaffy/utils.ex:363: Kaffy.Utils.convert_to_atom/1
        (kaffy 0.9.1) lib/kaffy/utils.ex:359: Kaffy.Utils.convert_to_atoms/2
        (kaffy 0.9.1) lib/kaffy/utils.ex:218: Kaffy.Utils.get_resource/3
        (kaffy 0.9.1) lib/kaffy_web/controllers/resource_controller.ex:55: KaffyWeb.ResourceController.index/2
        (kaffy 0.9.1) lib/kaffy_web/controllers/resource_controller.ex:1: KaffyWeb.ResourceController.action/2
        (kaffy 0.9.1) lib/kaffy_web/controllers/resource_controller.ex:1: KaffyWeb.ResourceController.phoenix_controller_pipeline/2
        (phoenix 1.6.2) lib/phoenix/router.ex:355: Phoenix.Router.__call__/2
        (dog_goal 0.1.0) lib/dog_goal_web/endpoint.ex:1: DogGoalWeb.Endpoint.plug_builder_call/2
        (dog_goal 0.1.0) lib/plug/debugger.ex:136: DogGoalWeb.Endpoint."call (overridable 3)"/2
        (dog_goal 0.1.0) lib/dog_goal_web/endpoint.ex:1: DogGoalWeb.Endpoint.call/2
        (phoenix 1.6.2) lib/phoenix/endpoint/cowboy2_handler.ex:43: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.9.0) /home/drobban/code/elixir/dog_goals/dog_goal/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.9.0) /home/drobban/code/elixir/dog_goals/dog_goal/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.9.0) /home/drobban/code/elixir/dog_goals/dog_goal/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 3.15.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

**Comment by aesmail** [comment]
@drobban does this happen in dev and prod or just dev?

**Comment by aesmail** [comment]
This is related to #140 which has a workaround

**Comment by drobban** [comment]
> @drobban does this happen in dev and prod or just dev?

Only tested in dev.

**Comment by drobban** [comment]
> This is related to #140 which has a workaround

Will read the thread and report back here.

Thanks for being a awesome project btw!
