### ISSUE TITLE
[BUG] No Actions

### ISSUE THREAD

**Issue by chuckwagoncomputing** [aesmail/kaffy#229]
**Versions Used**
Kaffy: #227
Phoenix: 1.6.7
Elixir: 1.13.2

There is no actions dropdown, even if I add custom actions.

If I understand correctly, there should be some actions, even by default.

![image](https://user-images.githubusercontent.com/1531127/167331448-0c490289-d4d1-463c-b45d-72df2a0da58b.png)

I'm new to Elixir, so maybe I've done something wrong, but I don't know what.

**Comment by chuckwagoncomputing** [comment]
Well I found why custom actions didn't work. It was a typo on my part, unsurprisingly. I still don't see any default actions such as delete. Are there supposed to be some?

**Comment by aesmail** [comment]
Kaffy doesn't currently have default actions. That would be a nice feature to have for v0.10 which is going to be released in a few weeks.
