### ISSUE TITLE
How to configure multiple selector field?

### ISSUE THREAD

**Issue by RafaelOFreitas** [aesmail/kaffy#245]
I have forms, with fields that accept an array, but I want to have control of which options are accepted, so the value options are listed by a query. 
How to configure the form to render a component of type `multiple_select` for these fields?

**Comment by aesmail** [comment]
Let's say you have a field named `things` which accepts an array of strings.

You can have this in the admin module for that schema:

```elixir
def form_fields(conn) do
  [
      title: %{update: :readonly},
      status: %{choices: [{"Available", "available"}, {"Sold out", "soldout"}]},
      things: %{
        type: {:array, :string},
        values_fn: fn _data, _conn -> [{"Option 1", "value1"}, {"Option 2", "value2"}] end
      }
  ]
end
```
