### ISSUE TITLE
How to perform view/edit on a custom setting value?

### ISSUE THREAD

**Issue by GildedHonour** [aesmail/kaffy#249]
Let's say, I have a single value or multiple ones that don't live in any Db table. 
They could be settings: page size, amount of days to wait before release of escrow, minimum allowed price, min  % of fees. The initial values of them could be set via env. variables and a config file. 
Namely, they're not proper models, or Db tables, such as User, Article and so on would be.

How to build a page for such values? I'd want to be able to a) view b) edit them; deletion wouldn't be required.

**Comment by aesmail** [comment]
@GildedHonour kaffy doesn't currently support these types of values yet, especially if you want to edit them. I have needed something like this though and I think I will implement this feature for the upcoming release.

**Comment by GildedHonour** [comment]
@aesmail is there a workaround in Kaffy?  I can't have 2 separate dashboards for the admins: one in Kaffy and a custom one for such  cases that Kaffy doesn't support. Therefore I want to implement it in the Kaffy dashboard *somehow*.

**Comment by aesmail** [comment]
@GildedHonour you can check if you can create a [custom page](https://github.com/aesmail/kaffy#custom-pages) for this. I would list all the values there and maybe create forms/buttons to set the values. It would require a bit of experimentation though.

**Comment by GildedHonour** [comment]
Thx
