### ISSUE TITLE
[FEATURE-REQUEST] filter {:array, :string} types

### ISSUE THREAD

**Issue by bitboxer** [aesmail/kaffy#254]
**Describe the problem you're proposing to solve**

I want to be able to filter `{:array, :string}` types for certain values

**Describe the solution you'd like**

The system should generate a correct sql statement for the current filter syntax when detecting an `:array` type

**Comment by aesmail** [comment]
Hey @bitboxer 
can you please provide more context as to how this would be used?
do you mean that you already tried the `filters` option but it's not behaving as expected with `:array` types?

**Comment by bitboxer** [comment]
I have an array string type. It has entries like "can_read_pages", "can_write_pages" and a couple of others. The editing part works amazingly smooth. But now I want to filter all rows that have "can_read_pages" in the array. the dropdown in the filter is filled with the correct value, I click it and then the sql statment it generates is invalid.
