### ISSUE TITLE
ID returns ERROR for some resources

### ISSUE THREAD

**Issue by axelclark** [aesmail/kaffy#26]
I've added kaffy to my exisiting project, see branch:  https://github.com/axelclark/ex338/tree/kaffy.

For some resources, the ID field on the form page displays ERROR when I click on the ID in the index list.  For example Ex338.Trade, Ex338.User, and Ex338.FantasyTeam. 

I don't receive the error for Ex338.SportsLeague, Ex338.FantasyPlayer, and Ex338.DraftPick.

Any ideas what the issue could be?

**Comment by aesmail** [comment]
Interesting and weird find. Not exactly sure why the ID field is being treated as an association field for some schemas and not for others. I'll need to do some deeper experimentations.
Released v0.6.1 which should fix this and some other issues.
Please feel free to reopen this issue if you're still having problems.

**Comment by axelclark** [comment]
I looked again and these schemas all have fields where the foreign key id doesn’t match the associated resource.

`has_many(:submitted_trades, Ex338.Trade, foreign_key: :submitted_by_team_id)`
