### ISSUE TITLE
[BUG] Unable to update records (404 error)

### ISSUE THREAD

**Issue by jcelliott** [aesmail/kaffy#264]
**Versions Used**
Kaffy: 0.9.4
Phoenix: 1.6.16
Elixir: 1.14.2

**What's actually happening?**

When I click "Save" to update a record I'm getting a 404 error. Looking at the network logs, it's trying to make a POST request to `/:context/:resource/:id` instead of a PUT request. I've tested on Firefox and Chrome to make sure it wasn't a browser issue.

```
[info] POST /admin/models/user/8a1af195-e606-4935-a39c-a7b38512dbcb
[info] Sent 404 in 7ms
[debug] Converted error Phoenix.Router.NoRouteError to 404 response
```

**What should happen instead?**

The record should be saved correctly. The frontend should be making a PUT request.

I see the router configuration [here](https://github.com/aesmail/kaffy/blob/db633a2d7df38f04955f4b01fdef08f39f17f5c6/lib/kaffy/routes.ex#L50) and the form configuration [here](https://github.com/aesmail/kaffy/blob/db633a2d7df38f04955f4b01fdef08f39f17f5c6/lib/kaffy_web/templates/resource/show.html.eex#L35), which both look correct to me. If anyone has pointers for somewhere else I should look please let me know.

**Comment by a3kov** [comment]
Make sure you have `Plug.Parsers` running before `Plug.MethodOverride`
The override will not work without the parsed body available

**Comment by jcelliott** [comment]
@a3kov thank you for the suggestion! That was indeed the issue. We have a complicated `Plug.Parsers` configuration due to some proxy requests we're handling, but the net result was the `_method` parameter wasn't getting parsed before `Plug.MethodOverride` was called.
