### ISSUE TITLE
Fixing CI

### ISSUE THREAD

**Issue by ghenry** [aesmail/kaffy#265]
@aesmail 

Can I drop some of these:

https://github.com/aesmail/kaffy/blob/master/.github/workflows/ci.yml#L15

failing in all our CI.

Then I want to merge some PRs and add to our CHANGELOG Unreleased section. That OK?

Thanks.

**Comment by aesmail** [comment]
@ghenry I think we could fairly safely remove Erlang 21 from the tests. We should also include the latest elixir versions (1.13 and 1.14). All versions need to be updated in the CI file honestly. But go ahead 👍🏻

Thank you

**Comment by aesmail** [comment]
@ghenry maybe we should roughly follow [elixir's official compatibility](https://hexdocs.pm/elixir/compatibility-and-deprecations.html) documentation.

Whether we will follow elixir's compatibility or not, we should make that clear in the README.

**Comment by ghenry** [comment]
Yeah, let's follow that. The issue is we're using `ubuntu-latest` which as per this doesn't have OTP 21:

https://github.com/erlef/setup-beam#usage

I'll switch use to `ubuntu-20.04` which is LTS anyway and good for many years:

https://wiki.ubuntu.com/Releases

That should get us back in the green.

**Comment by ghenry** [comment]
Yep, all green again. I've add this to our README too:

https://github.com/aesmail/kaffy/commit/101c2ee1339bdf8068c83eae40535bb7f29f37d8

Closing this now. Thanks for the speedy replies!

**Comment by aesmail** [comment]
Perfect! Thank you!
