### ISSUE TITLE
Consider removing id, inserted_at, and updated_at from default form

### ISSUE THREAD

**Issue by axelclark** [aesmail/kaffy#27]
By default, I would not expect `id`, `inserted_at`, and `updated_at` to be included in the form for creating a new record or updating an existing record.  I would consider removing these fields from the default form.

**Comment by aesmail** [comment]
I think this is a sound suggestion. Users can always include them when they need to through `form_fields/1`.
This change is coming in the next version.

**Comment by aesmail** [comment]
This is implemented in master. By default, the index and form pages will not show autogenerated fields. Those fields are by default `id`, `inserted_at`, and `updated_at`.
