### ISSUE TITLE
[FEATURE-REQUEST] Bulk Delete

### ISSUE THREAD

**Issue by kevinschweikert** [aesmail/kaffy#277]
**Describe the problem you're proposing to solve**
Currently, the only way to delete an entry is to open the form page for the given entry and then press the delete button

**Describe the solution you'd like**
I want to select multiple entries from the index page and bulk delete them

**Describe alternatives you've considered**
To use list actions, but you have to add it manually to every admin schema

**Comment by aesmail** [comment]
@kevinschweikert this has been implemented and will be available in the next release.
