### ISSUE TITLE
[FEATURE-REQUEST] - resolve deprecation warnings in Phoenix 1.7

### ISSUE THREAD

**Issue by arcanemachine** [aesmail/kaffy#280]
**Versions Used**
Kaffy: 0.9.4
Phoenix: 1.7.7
Elixir: 1.14.5-otp-26

**What's actually happening?**

When I run `mix deps.compile kaffy`, the following deprecation warnings appear:

1. `warning: the :phoenix compiler is no longer required in your mix.exs.`

2. `warning: Phoenix.Controller.get_flash/2 is deprecated. get_flash/2 is deprecated. Use Phoenix.Flash.get(@flash, key) instead`

**What should happen instead?**

There should be no deprecation warnings.

---

I believe that both deprecation warnings appeared in Phoenix `v1.7.0-rc.0`.

The first warning is referenced in [this commit](https://github.com/phoenixframework/phoenix/commit/9e0491ad92bd97c89aa94808659534786b8b17ea#diff-2c740742575f446c0ed96d398c767a07983f6aa6530d327a16b0b3790c0440e6).

For the second warning, the [current Phoenix changelog](https://github.com/phoenixframework/phoenix/blob/main/CHANGELOG.md#deprecations) indicates that the deprecation warning appeared in Phoenix `v1.7.0-rc.0`.

---

I understand that this project current supports Phoenix `>=v1.5.0` so removing the deprecated items probably isn't an option for now. I just wanted to put it on the record.

**Comment by aesmail** [comment]
Thank you @arcanemachine 
You're right. Kaffy currently supports the [officially maintained elixir versions](https://hexdocs.pm/elixir/1.15/compatibility-and-deprecations.html) (`>= 1.11` as of this writing) and phoenix `>= 1.5`.
I would love to get rid of the deprecation warnings if there's a way around it.
