### ISSUE TITLE
[BUG] :readonly option not working

### ISSUE THREAD

**Issue by roryfahy** [aesmail/kaffy#282]
**Versions Used**
Kaffy:  tried both  {:kaffy, "~> 0.9.2"}, and {:kaffy, github: "aesmail/kaffy"},
Phoenix: 1.7
Elixir: 1.15.3

**What's actually happening?**
`:readonly` value for `:create` and `:update` opts do not prevent writing as expected but instead allow updates/selections on create.  

Selecting `:hidden` works as expected

**What should happen instead?**
expected behaviour of not allowing writing values

**Screenshots**
![image](https://github.com/aesmail/kaffy/assets/42627486/72c311cc-cb52-4c41-9e78-1172146c1264)
![image](https://github.com/aesmail/kaffy/assets/42627486/87891fb5-1d59-4f22-9a32-16ae51e64976)

**Comment by aesmail** [comment]
@roryfahy a fix has been implemented and will be available in the next release. Thank you.
