### ISSUE TITLE
[FEATURE-REQUEST] Hide action buttons in show template

### ISSUE THREAD

**Issue by JessikaCastellano** [aesmail/kaffy#283]
**Describe the problem you're proposing to solve**

Certain scenarios require hiding actions within show templates. For instance, when the category is populated via integration or ETL, users should be able to view the categories list and details. However, modifying or deleting should not be enable

<img width="1499" alt="Screen Shot 2023-08-29 at 15 04 06" src="https://github.com/aesmail/kaffy/assets/37912327/110dd5c6-539e-453e-85b2-f7ebbe5f6089">

**Describe the solution you'd like**

Depending on the `default_actions` configure in resource hide the actions 

**Describe alternatives you've considered**

**Additional context**

I fork the repo and add the condition to the `show.html.eex`. Here is the [diff](https://github.com/Foris/kaffy/compare/master...JessikaCastellano:kaffy:master) 

I tested it out and this is how it looks when 

```
  def default_actions(_schema) do
    []
  end
```

<img width="1499" alt="Screen Shot 2023-08-29 at 15 14 11" src="https://github.com/aesmail/kaffy/assets/37912327/5afaf493-09de-4ba5-82c3-1e4aa282bdac">

**Comment by aesmail** [comment]
@JessikaCastellano Thank you. This has been implemented and will be available in the upcoming release.
