### ISSUE TITLE
Resource with two words doesn't save properly

### ISSUE THREAD

**Issue by axelclark** [aesmail/kaffy#29]
When I submit a form for a resource with two words in the name, I receive an error that all required forms are blank.  

It appears in might be an error with the two words not separated with an underscore in the parameters:

```elixir
  Parameters: %{"_csrf_token" => "XiADUzgRR1JoGh4TRC8YCgEPETRoK1l5hMV7Yy341lQ87Zs26W_N_jdD", "championship_result" => %{"championship_id" => "52", "fantasy_player_id" => "531", "id" => "", "inserted_at" => %{"day" => "1", "hour" => "0", "minute" => "0", "month" => "1", "year" => "2015"}, "points" => "8", "rank" => "1", "updated_at" => %{"day" => "1", "hour" => "0", "minute" => "0", "month" => "1", "year" => "2015"}}, "context" => "ex338", "resource" => "championshipresult", "submit" => "Save"}
```

See `"championship_result" => %{"data" => "data"}` & `"resource" => "championshipresult"`.

I was able to save my "owners" resource, but also couldn't save my "fantasy_leagues" resource.

Successful `owners` resource:
```elixir
  Parameters: %{"_csrf_token" => "bz0tFhQPPDlrLwx-JR8iWg4rJz1_Lw5lYPxrugH_2YCUVjIb9siGHn3X", "context" => "ex338", "owner" => %{"fantasy_team_id" => "53", "id" => "", "inserted_at" => %{"day" => "1", "hour" => "0", "minute" => "0", "month" => "1", "year" => "2015"}, "updated_at" => %{"day" => "1", "hour" => "0", "minute" => "0", "month" => "1", "year" => "2015"}, "user_id" => "2"}, "resource" => "owner", "submit" => "Save"}
```

**Comment by aesmail** [comment]
Thank you @axelclark !
Your reported issues are making kaffy much better!
I have always tried, for some reason, to stick to "single-word" resources subconsciously.

I will fix this in the next release which should be within a few hours.

**Comment by aesmail** [comment]
This is fixed in master.
v0.6.2 will be released shortly.

**Comment by aesmail** [comment]
v0.6.2 released.
