### ISSUE TITLE
[BUG] readonly also not working with dropdown fields

### ISSUE THREAD

**Issue by roryfahy** [aesmail/kaffy#292]
**Versions Used**
Kaffy: {:kaffy, "~> 0.10.rc.2"}
Phoenix: 1.7
Elixir: 1.15.3

**What's actually happening?**
Thank you very much for fixing the :readonly issue with datetime type fields #282 .  I should have reported this more clearly in the previous issue I opened but the issue also occurs with dropdown selection fields.

**What should happen instead?**
they should also be readonly if configured so

**Screenshots**
![image](https://github.com/aesmail/kaffy/assets/42627486/c328c71e-8d99-4cc0-8e72-7b2f89de5078)
![image](https://github.com/aesmail/kaffy/assets/42627486/19494276-40cb-4b81-a745-0e5d3ae75383)

**Comment by aesmail** [comment]
@roryfahy thanks for reporting these issues. They're making Kaffy better and more inline with what is expected out of it. I'll make sure this is solved before v0.10 final.
