### ISSUE TITLE
Handle search_fields from relationships

### ISSUE THREAD

**Issue by antonioparisi** [aesmail/kaffy#30]
Hi @aesmail - hope you're well.

Imagine this scenario
User belongs to Profile

User has got email and a couple of other fields
Profile has got first name, last name etc.
on Kaffy I'm not gonna have two resource tabs called `Users` and `Profiles`. I will only have `Users`, right?
Users resource will show also user's profile first/last name, etc.

I would like to be able to search by user's profile first/last name, email, etc

if that make sense? 👍

**Comment by aesmail** [comment]
Hello @antonioparisi 
Thanks for the suggestion. This is actually on the roadmap as this is one of the features I use most with django's admin.
Django uses the double-underscore notion to indicate a search across an association:
`search_fields: ['email', 'profile__last_name']`
This means include the `email` field and the `last_name` field (which is from the `profile` association) in the fields to search for.

I might adopt a similar approach to this. I'm also open for suggestions.

**Comment by antonioparisi** [comment]
the approach you suggested sounds good to me - thanks @aesmail 
PS: Kaffy is looking amazing so far

**Comment by aesmail** [comment]
This is done in master and will be released in the next version 👍🏼.
Basically, to search across associations, you need to specify the fields:

```elixir
# User schema
def search_fields(_) do
  [
    :email,
    :other_field,
    profile: [:first_name, :last_name]
  ]
end
```

Search section updated in README.
