### ISSUE TITLE
Consider removing "virtual" schema fields from default form

### ISSUE THREAD

**Issue by axelclark** [aesmail/kaffy#31]
Ecto.Schema.field/3 has an option to label `virtual: true` for when the field is not persisted to the database.  See https://hexdocs.pm/ecto/Ecto.Schema.html#field/3.

Suggest removing these `virtual` fields from the default form.

**Comment by aesmail** [comment]
I actually do use virtual fields for holding temporary values when creating new records. I'll leave this open for reference and further discussion.

**Comment by aesmail** [comment]
I'll explain my reasoning. In some schemas, I need to validate some temporary values entered by the user and, after successful validation and processing, I don't need to keep that value.
Example: the user must submit a currency identifier (e.g. USD). I take that value and validate it (3 letters, [A-Z]+, etc. Then do some processing based on that value and discard of it.

**Comment by aesmail** [comment]
Closing this for now to cleanup the issues a bit.
