### ISSUE TITLE
Release new Version for Phoenix.HTML 4.0

### ISSUE THREAD

**Issue by PJUllrich** [aesmail/kaffy#316]
Hey folks, it seems like you updated the `phoenix_html` dependency to `~> 4.0` but [without a version bump](https://github.com/aesmail/kaffy/commit/66d0c7d135dc68111acfbc0b9ac3b798067cef63) or a Hex.pm release. Would you mind bumping the version and releasing it to Hex, please? Otherwise, the latest version `0.10.2` on Hex still depends on `phoenix_html ~> 3.0`. Thank you!

**Comment by re-masashi** [comment]
any updates on this?

**Comment by nathany-copia** [comment]
Currently running with a commit on GitHub until there is a new release to Hex.

```
{:kaffy, github: "aesmail/kaffy", ref: "d864ea1"},
```

**Comment by hagenek** [comment]
The maintainer as effectively abandonened this project?

**Comment by bglusman** [comment]
I hope not!  but, if so, anyone want to propose a better supported fork?  either an existing one, or volunteers to help try and maintain a new fork? We're using this at Pepsi, so, I guess I might volunteer us for this if needed, but, if there's any existing work or forks elsewhere, good to know, we're blocked by this also so, about to use our own fork for now, TBD long term plan...

**Comment by ghenry** [comment]
Hi all,

I have commit access. What do we need?

Thanks.

**Comment by bglusman** [comment]
Oh hey!  I think its not commit access we need but, ideally just a new hex release cut, so people don't need to rely on a random sha to get latest changes, including dep updated for phoenix_html?

**Comment by ghenry** [comment]
Let me check I can do that bit too.

**Comment by ghenry** [comment]
I'm asking for hex.pm perms. Will let you know.

**Comment by ghenry** [comment]
No reply re hex.pm perms yet. Sorry guys.

**Comment by kelcecil** [comment]
I think I have Hex access for Kaffy. Let me check in a bit and get back to the group.

Thanks!
Kel Cecil

**Comment by kelcecil** [comment]
Oh... I'm apparently a package owner... I think I may actually be able to add you @ghenry. PM me your hex user name, and I'll see if I can add it...

FWIW, I have this access because we used Kaffy at InspectionGo, and we ran into an issue before where we had provided changed that hadn't made it to a hex package. We've started divesting from kaffy, and I periodically think about a LiveView-powered admin dash that's a bit more flexible when you're working with architectures like CQRS and event sourcing (which was a bit crunchy for us).

**Comment by kelcecil** [comment]
Looks like someone else added @ghenry. I'm guessing @aesmail  as I didn't. I'm pushing a 0.10.3 to hex with the changes in head now.

**Comment by aesmail** [comment]
@kelcecil thanks for the release. I added @ghenry to hex. I wasn't aware of this thread until you mentioned me.

**Comment by ghenry** [comment]
Thanks everyone and thank you @kelcecil for doing the release!

**Comment by ghenry** [comment]
Do we normally create a release on GitHub too or just hex?

**Comment by kelcecil** [comment]
@ghenry I never did a release on Github just because they hadn't been done when I joined. I think you could tag releases if you wanted though.

**Comment by hagenek** [comment]
Great job ghenry, thanks!

**Comment by nathany-copia** [comment]
`{:kaffy, "~> 0.10.3"}` 

thanks
