### ISSUE TITLE
@resource_name in update action assumes single word resource

### ISSUE THREAD

**Issue by axelclark** [aesmail/kaffy#32]
In the update form `ChampionshipResult` displays as `Championshipresult`.  It displays correctly in the new form as `ChampionshipResult`.

See: https://github.com/aesmail/kaffy/blob/8ae0767ee2d05f3d5e51536643f774848f2fb616/lib/kaffy_web/controllers/resource_controller.ex#L88

Seems related to https://github.com/aesmail/kaffy/issues/29

The issue doesn't seem to affect successful submission of the update form.

**Comment by aesmail** [comment]
This is done in master and is much improved:

`ChampWithEventsResult` becomes "Champ With Events Result".
`DraftPick` becomes "Draft Pick".
`Trade` becomes "Trade".
