### ISSUE TITLE
Default value from changetset

### ISSUE THREAD

**Issue by areski** [aesmail/kaffy#35]
I'm new to Phoenix so I can easily say something **very stupid**.

Here a demo project to show an issue I'm seeing.
https://github.com/areski/ex-chitchat/blob/master/lib/chit_chat/blog/post.ex#L20

**The `Unique UUID` is empty in Kaffy admin page:**

![image](https://user-images.githubusercontent.com/53455/82691444-351a5b00-9c5e-11ea-8f6c-f5902f352455.png)

**But it will work fine with Phoenix Generated template:**

![image](https://user-images.githubusercontent.com/53455/82691518-5418ed00-9c5e-11ea-98c6-149bb47f698f.png)

Any advice to fix that?

**Comment by aesmail** [comment]
This might be a bug from kaffy's side. I'll check it out.

Could you please confirm that if you set a default value for the title and/or views field these values show up in kaffy's form?

**Comment by aesmail** [comment]
I figured it out. Kaffy wasn't using the module's default `changeset/2` when creating new records. A fix is coming shortly.

**Comment by areski** [comment]
Thanks for looking into this, take the time you need.
I tried with your last release v.0.7.1

Now as soon as I try to create a new Post, or an other entity. 

I see the following screen:

![image](https://user-images.githubusercontent.com/53455/82702812-02c72880-9c73-11ea-90a0-cbcfb5a68f45.png)

I have the feeling we have broken something.

**Comment by aesmail** [comment]
We just need to hide the errors from the new resource page.
But I noticed something else, now Blog/Posts and Room/Rooms show "category" in the URL. I'm not sure yet why that is happening.

**Comment by aesmail** [comment]
This is fixed in master 👍🏼.
Please feel free to re-open it if you find anything weird.

**Comment by areski** [comment]
Now it gives me the warning just after I click on "save" button, before it gave the warning as soon as I arrive on the add view.

![image](https://user-images.githubusercontent.com/53455/82709122-2f357180-9c80-11ea-861d-ee14f4dc6da6.png)

**Comment by areski** [comment]
I cannot reopen the issue unfortunately.

**Comment by aesmail** [comment]
Can you confirm that the URL for the posts page is `/admin/blog/category`? If this is the case, this is the reason why it's not saving properly and I need to fix it.

**Comment by aesmail** [comment]
Ok, figured out why it's like this and a fix is coming.

**Comment by aesmail** [comment]
In the mean time, you could change the configs for the `Room` and `Post` schemas and replace `category` term in both fields with their correct names `room` and `post` [here](https://github.com/areski/ex-chitchat/blob/642add1a5c8096762e24f55ec7d9be584b188374/config/kaffy.exs#L27).

**Comment by aesmail** [comment]
I will close this issue and reopen another issue with the actual problem.

**Comment by areski** [comment]
Here what I did which took me sometime to figure out as I thought it was an issue with the changeset.

```elixir
resources: [
    blog: [
      name: "Blog",
      schemas: [
        blog: [schema: ChitChat.Blog.Post, admin: ChitChatWeb.PostAdmin]
      ]
    ]
  ]
```

I used the same name term `blog` directly under `resources[]` and also under `schemas[]`, this creates a conflict and although it will display the form correctly it will not validate it, thus getting error as below:
![image](https://user-images.githubusercontent.com/53455/82808116-8eb29d80-9e89-11ea-82d5-72a34f4d9b10.png)

I was wondering why is the key name choice so important? Why it could not be the same as the key name under resource.
I imagine this is made by design, just wondering if we could avoid other users to not fall in the same trap as I did.

**Comment by aesmail** [comment]
The “blog” under schemas should be “post”, like the schema name. But yeah, it should not matter. This is what issue #37 is trying to fix.

**Comment by aesmail** [comment]
Or you could entirely remove the resources section from the configs and Kaffy will correctly figure out the schemas and their admin. This will include all schemas though, which might not be the desired outcome.

**Comment by areski** [comment]
The concern was more towards avoid errors when getting started, I understand how it can be fixed now... just mentioning here so that ppl don't fall in the same trap.
Glad that #37 will take care of this
