### ISSUE TITLE
Manually listing schemas with keys different than the actual schema module name leads to unexpected behavior

### ISSUE THREAD

**Issue by aesmail** [aesmail/kaffy#37]
When we have `Blogs.Post` and `Rooms.Room` schemas and define them like this in kaffy:

```elixir
resources: [
    room: [
      name: "Room",
      schemas: [
        example: [schema: ChitChat.Chat.Room, admin: ChitChatWeb.RoomAdmin]
      ]
    ],
    blog: [
      name: "Blog",
      schemas: [
        test: [schema: ChitChat.Blog.Post]
      ]
    ]
  ]
```

Kaffy will not be able to create/update schemas correctly.
Currently, kaffy uses the `schemas` keys to construct URLs which it shouldn't.

We need a fix for now, but we also need to evaluate having atom keys in the `schemas` list since they are becoming irrelevant. The previous example could be written as follows:

```elixir
resources: [
    rooms: [
      name: "Room",
      schemas: [
        [schema: ChitChat.Chat.Room, admin: ChitChatWeb.RoomAdmin]
      ]
    ],
    blogs: [
      name: "Blog",
      schemas: [
        [schema: ChitChat.Blog.Post]
      ]
    ]
  ]
```

**Comment by areski** [comment]
My 2 cents here, maybe it might be good to think without rush on this one to get it right.

What about something like:
```elixir
config :kaffy,
  admin_title: "Admin Portal",
  otp_app: :chit_chat,
  ecto_repo: ChitChat.Repo,
  router: ChitChatWeb.Router,
  admin_config: [
    [
      section_name: "Accounts",
      order: 1,
      resources: [
        [title: "User", schema: ChitChat.Accounts.User, admin: ChitChatWeb.UserAdmin],
        [title: "Credential", schema: ChitChat.Accounts.Credential, admin: ChitChatWeb.CredentialAdmin]
      ]
    ],
    [
      section_name: "Chat",
      order: 2,
      resources: [
        [title: "Room", schema: ChitChat.Chat.Room, admin: ChitChatWeb.RoomAdmin]
      ]
    ]
  ]
```

On a side note, not sure how config.exs works with I18n, maybe something to think about.

Thanks for your great work :1st_place_medal:

**Comment by aesmail** [comment]
This needs way more thinking than I expected.
One thing though is that, with lists in elixir, you don't need the `:order` key since the order is preserved, unlike maps.

**Comment by areski** [comment]
Some decision doesn't need to be taken too quickly :)
Thanks for the info on order :+1:

**Comment by aesmail** [comment]
This is related to #122 
It doesn't address the "misnaming" problem, but that should be clear in the docs.
