### ISSUE TITLE
[FEATURE-REQUEST] Add export functionality

### ISSUE THREAD

**Issue by aesmail** [aesmail/kaffy#4]
I'm interested in exporting data as csv.

Maybe something like:

```elixir
def export_fields(schema, params) do
  entries = Kaffy.ResourceAdmin.list_resource(schema, params)
  fields = [:id, :title, :status, :inserted_at]
  for entry <- entries do
    # ...
  end
end
```

**Comment by msp** [comment]
Did you make any progress on this?

Doing it safely would require an async task and storing the CSV somewhere. 

Perhaps a synchronous operation with a safe upper limit would suffice for may usage..

**Comment by ghenry** [comment]
@msp we're struggling at the moment. If you have any time to work on this, that would be much appreciated!

**Comment by msp** [comment]
> @msp we're struggling at the moment. If you have any time to work on this, that would be much appreciated!

Ah sorry, I've got my hands full right now. I'll lyk if that changes.

**Comment by ghenry** [comment]
No worries! You're welcome back any time 😁
