### ISSUE TITLE
[FEATURE-REQUEST] Checkboxes in index page to visually indicate that rows are selectable.

### ISSUE THREAD

**Issue by areski** [aesmail/kaffy#41]
It might be nice to have checkbox next to the list of element to apply batch action, eg, `delete all the selected` or some custom batch action

For reference on django-admin
![image](https://user-images.githubusercontent.com/53455/82756666-d2e76480-9ddb-11ea-98a1-6bed1f4a89de.png)

**Comment by aesmail** [comment]
This is really needed since currently it's not clear that you could select rows and perform batch actions on them.

**Comment by areski** [comment]
I had no idea, I see it was mentioned in the Readme now, but yes user of the admin portal might not be developer they would need a type of hint

**Comment by aesmail** [comment]
This is done in master. It works, but I'm not 100% happy with it. It needs to be improved in later versions.
Currently, you cannot select records from multiple pages which might not be that important, but it was a nice feature from datatables.

**Comment by areski** [comment]
I think we can live well without the checkbox working on pagination, I would not have expected it to work in that case.
Thanks a million!
