### ISSUE TITLE
Using Liveview on the Dashboard

### ISSUE THREAD

**Issue by areski** [aesmail/kaffy#42]
A good example of that might be the new built-in dashboard:
https://github.com/phoenixframework/phoenix_live_dashboard

Watch it autorefresh, really something I would want to see

**Comment by aesmail** [comment]
I was thinking of providing built-in support for telemetry events. If we do this, along with liveview support, it would kind of put Kaffy as a direct "competitor" with the built-in live_dashboard.

**Comment by areski** [comment]
I'm closing this issue for now, I think we can reopen it when the time is right

**Comment by Nezteb** [comment]
I assume https://github.com/aesmail/kaffy/issues/43 supercedes this issue? 😅
