### ISSUE TITLE
[FEATURE-REQUEST] Use different Admin Template mobile friendly (Tailwind CSS/Bootstrap4)

### ISSUE THREAD

**Issue by areski** [aesmail/kaffy#44]
The dashboard looks nice, but probably tailwindcss will provide a higher level of customization.
Additionally I found that SB-Admin is not very nice on mobile, I know there is a small audience using backend on mobile, nevertheless if we could tackle this early rather than later it would be awesome

[https://www.creative-tim.com/learning-lab/tailwind-starter-kit/dashboard] 
![image](https://user-images.githubusercontent.com/53455/82756999-f4e1e680-9ddd-11ea-9a75-cbde0a4e43d3.png)

Above Create-Tim is providing a skel for Dashboard which is MIT licensed. It might be a good fit, although it would be worth doing more research.

**Comment by aesmail** [comment]
> I know there is a small audience using backend on mobile

I actually got more comments than expected from people "complaining" that it doesn't render nicely on mobile. So your point is valid.

**Comment by aesmail** [comment]
I am hesitant a little bit about this suggestion. Looking into the tailwind ecosystem, although it's nice and very promising, it hugely lacks the size and support that other popular frameworks have, like bootstrap and foundation for example. This might make it a little bit harder or inconvenient to contribute to kaffy or create some extensions.

**Comment by areski** [comment]
It's a very valid, point... I was also a bit concerned about it to be frank.
Maybe one we need it's to find a good replacement to sb-admin which work better on mobile.

There is coreui for instance.

Here a list https://dev.to/sm0ke/admin-dashboards-open-source-and-free-4aep

It might be to do some research if we find a better fit that is MIT licensed.

**Comment by aesmail** [comment]
I'm leaning towards [CoreUI](https://coreui.io/demo/3.1.0/#main.html) and [Material Dashboard](https://demos.creative-tim.com/material-dashboard/examples/dashboard.html).

I feel that Material Dashboard is much cleaner, yet CoreUI has a lot of extra components that could be used currently and in the future. Personally, I'd go with cleaner.

One missing point with Material Dashboard is the menu subitems. However I feel that could easy be added.

**Comment by areski** [comment]
A pity we could not talk/debate more before moving ahead, I see you implemented https://github.com/BlackrockDigital/startbootstrap-sb-admin 
To my opinion this feels like a step back in terms of design (personal taste of course), I would agree that the left menu is better but the rest feel like a downgrade.

I was doing some research yesterday to find a good replacement.
The main points to tick might be:  
MIT license, based on Bootstrap4, nice default form, good render on mobile devices, modern look&feel (although this is very subjective)

Here some options:
- Start-Admin & Purple: https://www.bootstrapdash.com/bootstrap-free-admin-templates/
  Overall good, nice on mobile and the default theme for form and table are good enough
- Adminator - https://github.com/puikinsh/Adminator-admin-dashboard
  Although a bit to white for my taste, it ticks a lot of box

Now looking at https://github.com/BlackrockDigital/startbootstrap-sb-admin-2 in the original template there is a top bar, I understand it was tempting to remove it.
![image](https://user-images.githubusercontent.com/53455/83008991-59878600-a016-11ea-9f1d-bdfc04d9ae47.png)
That small menu icon allow you to hide the menu:
![image](https://user-images.githubusercontent.com/53455/83009050-6dcb8300-a016-11ea-8488-dde6fa1c4b96.png)

There is an issue that explain how to hide the left menu by default:
https://github.com/BlackrockDigital/startbootstrap-sb-admin-2/issues/335

So probably if the motivation to move to an other template is only the mobile rendering, I would advice we consider hacking the left menu to improve it and try to mimic the behaviour, for instance opening down the menu:
![image](https://user-images.githubusercontent.com/53455/83009579-40330980-a017-11ea-9185-58e578eb0044.png)

**Comment by aesmail** [comment]
Rest assured, this is not the design I want for kaffy. I will not take UI decisions without pinging you first 😄. I actually was waiting for your opinion on this. This is why it's still open. I don't trust my design choices and, as mentioned before, this is my weak point. I did it to see how long it would take to port to a new design and for you to try it out and provide feedback.

I don't like the overall design either and liked the light colors of the previous design better. The port took about 1 hour or so. I checked both designs (star-admin and adminator) before getting sb-admin and I liked them both (leaning more towards adminator).

**Comment by areski** [comment]
There can be nice alternatives indeed.

Unfortunately Adminator behave weirdly on vertically on some mobile size:
![image](https://user-images.githubusercontent.com/53455/83028155-56e65a00-a031-11ea-9688-e10d5e2f582d.png)
Fonts are super small, when you turn the device in horizontally the problem goes away.

star-admin-free is very nice, but they don't have icon in the menu and it's not hideable on big screen, a feature I personally like

Purple tick a lot of boxes: https://www.bootstrapdash.com/demo/purple-admin-free/pages/forms/basic_elements.html | https://github.com/BootstrapDash/PurpleAdmin-Free-Admin-Template
Although it's too white and also the gradient is something out of horror movie that should be fixable.

Hard to find the perfect one under MIT license.

**Comment by aesmail** [comment]
I'm not too familiar with using licenses with open source projects. Is there an option to get a paid template (with a license other than MIT) and include it in kaffy? If so, do you recommend any templates?

**Comment by areski** [comment]
Including code in a project that is freely distributed is tricky, you need the license of the code that you will include to be permissive enough. That will not be an option for something that you can purchase as they will not want to let you distribute it freely.
https://tldrlegal.com/ most of the one we looked at are MIT https://tldrlegal.com/license/mit-license
Which will be perfect to include into Kaffy

**Comment by aesmail** [comment]
> the gradient is something out of horror movie that should be fixable.

😂

I find it nice, although yes it's a bit too white.
We could always tweak it.

**Comment by aesmail** [comment]
Whatever we chose, it will probably be modified to some extent. I'm very interested in closing this as soon as possible because I feel other issues will depend on it to some degree. I trust your judgement in this regard, so I'll go with whatever template you feel fits Kaffy the most.
This is what I think of the designs:

- CoreUI: I like the professional look of it. It has TONS of components that could be very beneficial and give Kaffy an edge with customizations and options. I like it a lot. Thinking loudly here, but it might be the easiest to work with when Kaffy has support for telemetry and LiveView.
- Purple: Clean, simple, although the colors of it can potentially be very "off" when integrated with other websites. I wish CoreUI had Purple's feel and simplicity. But between them, I'd choose CoreUI.
- Star Admin: It might be the closest to the original design of Kaffy in terms of color/layout combination. The lack of a built-in way to hide the side-menu on desktop might mean this is a "no" by default. But I like the collection of components (second to CoreUI) and the amount of icons it supports. I would definitely change the main color though since it feels a little bit too "saturated"? (if that's actually the meaning I'm trying to think of).
- Adminator: I like its simplicity very much. It has a nice combination of widgets/components. The fact that it doesn't render nicely on some non-typical screen sizes might not be a deal-breaker. I tried it on a few iOS simulators (iPad and iPhone X) and it displays correctly. I agree that fonts are smaller than normal, but personally I like smaller fonts in general, specially if I can control it to my taste.

Eventually, I'd like to go with something else other than (sb-admin) to something more complete and cleaner. I vote for (1) CoreUI and (2) Adminator.

What do you think?

**Comment by areski** [comment]
I could not agree more with more of your comments, thanks for sharing.
CoreUI has a lot of components but in reality they are just showing what bootstrap4 can do, they just spend more time copying all the bootstrap components.

I really like the icons in the menu staying when closing the menu on desktop view, I found this style giving a very neat and professional feeling, the way you had it originally with Kaffy.

I've been working the last hours on Purple, I think it has potential, so I tried to fix few things in the style to match the original style of Kaffy.
https://github.com/areski/PurpleAdmin-Free-Admin-Template

That's how it looks:
![image](https://user-images.githubusercontent.com/53455/83051085-c702d900-a04d-11ea-98b4-c2ce2550ab20.png)

Menu closed:
![image](https://user-images.githubusercontent.com/53455/83051217-f74a7780-a04d-11ea-8250-daf45d82b610.png)

I was just working on a nice palette:
![image](https://user-images.githubusercontent.com/53455/83051297-1b0dbd80-a04e-11ea-9a7a-c9999fe01b16.png)

On Mobile when opening the menu:
![image](https://user-images.githubusercontent.com/53455/83051455-590ae180-a04e-11ea-8810-5b6bf510ef2d.png)

I'm not a designer... so everything is really subjective to my taste :smile: 

I still want to import the shadow on the card element as you had before:
![image](https://user-images.githubusercontent.com/53455/83051659-9b342300-a04e-11ea-9335-d7143e4a74bc.png)

Comments will be welcome, you can fork https://github.com/areski/PurpleAdmin-Free-Admin-Template and play with it too if you think we are in the right direction.

**Comment by areski** [comment]
and Voila! 
Just added the shadow & also the left/bottom colored border which looked awesome on the first kaffy dashboard:

![image](https://user-images.githubusercontent.com/53455/83056027-fb2dc800-a054-11ea-8631-fd8bcc49e6ed.png)

added also a shadow on the navbar and copied the same color background, the previous one was too grey.

![image](https://user-images.githubusercontent.com/53455/83056173-3cbe7300-a055-11ea-8ab7-d83e7fa47a00.png)

The icon is the one of Purple template, we could use that for now and replace it by a future icon.

See what you think and let me know

**Comment by aesmail** [comment]
Amazing work Areski! It's hard to believe you're not a designer. That settles it. We will use this template. I'll replace the current design with yours. The next 24 hours will be interesting for Kaffy. Thanks a lot 👍🏼.

**Comment by areski** [comment]
Glad to help, I will leave that with you then!

**Comment by areski** [comment]
This is just amazing, great accomplishment in such a short time! 
Can't wait to see how Kaffy will look in the coming weeks :smile: 
Thanks!
