### ISSUE TITLE
[PROPOSAL] provide support for telemetry

### ISSUE THREAD

**Issue by aesmail** [aesmail/kaffy#45]
Since telemetry is becoming the de facto package for metrics and instrumentations in elixir, I feel it's going to provide a huge benefit for developers/admins using Kaffy if we have built-in support for it.

Also note the the official phoenix_live_dashboard uses this to provide useful metrics.

**Comment by aesmail** [comment]
I'm having second thoughts about this. I'm kind of leaning towards closing this and labeling it as "wontfix".
Do we really need telemetry support?

The built-in phoenix live support provides so much out of the box and is getting updated regularly.

What would be the benefit of of providing telemetry support if the phoenix_live_dashboard exists and comes bundled with phoenix and is getting updates by the community?

cc @areski

**Comment by areski** [comment]
My 2 cents...
We should ensure that Kaffy is flexible enough to display dashboard with data from any sources, which should already be the case, so a built-in telemetry support doesn't seem important to me.

I would be in favour of closing this issue too.
If the need raise in the future it could be reopen!

Cheers!

**Comment by areski** [comment]
I closed it, hope you don't mind

**Comment by aesmail** [comment]
I like closing issues more than opening them 🙏🏻

**Comment by areski** [comment]
I took that away from you :laughing:
