### ISSUE TITLE
[FEATURE-REQUEST] Create custom page

### ISSUE THREAD

**Issue by areski** [aesmail/kaffy#47]
It would be great to have the ability to create your own custom page, eg to build a custom report, or something very specific for someone business needs.

That customer page should be displayed inside the kaffy-admin, not on a different page.
Would love to see that.

**Comment by aesmail** [comment]
Custom pages are in master.

```elixir
defmodule MyApp.Products.ProductAdmin do
  def custom_pages(_schema, _conn) do
    [
      %{
        slug: "my-own-thing",
        name: "Secret Place",
        view: MyAppWeb.ProductView,
        template: "custom_product.html",
        assigns: [custom_message: "one two three"], # optional
        order: 2 # optional
      }
    ]
  end
```

If there are custom pages, a new side menu is created like the following:
![Screen Shot 2020-06-01 at 06 31 33](https://user-images.githubusercontent.com/602354/83373732-0cb6fd00-a3d2-11ea-819e-aec9668ffda7.png)

The link to the "Secret Place" page is https://example.com/admin/p/my-own-thing


The result page:

![Screen Shot 2020-06-01 at 06 31 22](https://user-images.githubusercontent.com/602354/83373747-180a2880-a3d2-11ea-9876-88d3b1376563.png)

It needs a few menu style enhancements, but it's done and I can finally close this.

**Comment by aesmail** [comment]
I was thinking about this today, and I'm starting to realize how powerful this could be. I definitely want to work on more improvements to custom pages in later versions.
