### ISSUE TITLE
Support for embedded schemas and map fields

### ISSUE THREAD

**Issue by aesmail** [aesmail/kaffy#5]

**Comment by tfwright** [comment]
Currently get an error viewing a schema with two json fields, one a plain map and another an embedded struct:

```
field(:subscriptions, :map, default: %{})

embeds_one(:notification_settings, Accounts.NotificationSettings)
```

The error message mentions a Map so I'm guessing that's what's triggering the error:

```
Protocol.UndefinedError: protocol Phoenix.HTML.Safe not implemented for %{} of type Map. This protocol is implemented for the following type(s): Decimal, Phoenix.LiveView.Rendered, Phoenix.LiveView.Comprehension, Phoenix.LiveView.Component, Float, Time, BitString, Phoenix.HTML.Form, Atom, DateTime, NaiveDateTime, Integer, Date, List, Tuple
```

**Comment by aesmail** [comment]
I have a quick fix for this issue.
I just need to make sure it's working properly and provide some tests and we're good to go. I will hopefully release a new version with this fixed in the next few days.

**Comment by aesmail** [comment]
This is included now in master. Releasing a new version today.
