### ISSUE TITLE
[FEATURE-REQUEST] Custom type field: image, audio, etc...

### ISSUE THREAD

**Issue by areski** [aesmail/kaffy#54]
We might want to consider keeping in mind when drafting kaffy for extendability.
For instance in Django-admin I have built this addons years ago to upload audio files  https://github.com/areski/django-audiofield

Similar django-admin addons exists to upload images, videos etc...

This type of addons, give some flexibility in building a custom display for the file you are uploading, add some custom javascript.

**Comment by aesmail** [comment]
I couldn't agree more. Already testing something locally for this. Will have a new branch for it this week hopefully.

**Comment by areski** [comment]
Thanks, take all the time you need!

**Comment by areski** [comment]
For future reference, I have an example of custom image field on a test project:
- https://github.com/areski/ex-chitchat/blob/master/lib/chit_chat_web/helpers/custom_image_field.ex
- https://github.com/areski/ex-chitchat/blob/master/lib/chit_chat_web/admin/upload_admin.ex

The upload of images created thumbnail and fill up few fields for size/content_type.

With our new ability to overload field, save, update etc... the integration with Kaffy is perfect.

![image](https://user-images.githubusercontent.com/53455/84596001-605a2980-ae5b-11ea-84df-9268b2d529ee.png)

Update of image also display the current image:

![image](https://user-images.githubusercontent.com/53455/84596021-7d8ef800-ae5b-11ea-987e-9d3a1e44d172.png)

YES! :rocket: :rocket: :rocket: :rocket: :rocket:

**Comment by aesmail** [comment]
Haha that is awesome! 🙏🏻💪🏼
