### ISSUE TITLE
[FEATURE-REQUEST] Filtering produce and use query parameters

### ISSUE THREAD

**Issue by areski** [aesmail/kaffy#55]
I feel that filter should produce an exchangeable URL, either for bookmark purpose or to send to someone, maybe we could use ex_sieve to achieve it:
https://github.com/valyukov/ex_sieve

**Comment by aesmail** [comment]
This is implemented in master now. Got rid of datatables and had to reimplement almost all functionality from scratch. And this issue was resolved as a result. It's not as advanced as ex_sieve, but it does the job for now.

**Comment by areski** [comment]
YESSSS !!! Thanks you
