### ISSUE TITLE
[DOC] Extra doc for embed & map

### ISSUE THREAD

**Issue by areski** [aesmail/kaffy#60]
it would be useful to have some documentation on the type of inputs.
Specially the `embed` & `map`
https://github.com/aesmail/kaffy/blob/master/lib/kaffy/resource_form.ex#L78

**Comment by aesmail** [comment]
You're right. Embedded schemas are mentioned briefly at the end of the [Form Page](https://github.com/aesmail/kaffy#form-page) section. But both embeds and maps need to be highlighted in a better way.

**Comment by areski** [comment]
For a phoenix beginner, it's hard to make sense to this:
`settigns is an embedded schema. That's why it is rendered as such.`

Not sure how to use it or what is it for.

No rush, but when you have time to document it, that would be awesome :relaxed:

**Comment by aesmail** [comment]
Agree 100%. To be honest, I never used embedded schemas before #5 was reported. They're extremely helpful for what they do. I started using them in my own projects after that 😁.
