### ISSUE TITLE
[BUG] all side menu items are always active (expanded) when visiting the dashboard page

### ISSUE THREAD

**Issue by aesmail** [aesmail/kaffy#63]
@areski do you have any idea what's going on here?
I went crazy yesterday because of this. I'm not sure if this is css or js related since adding/removing classes to the items doesn't seem to change anything.

**Versions Used**
Kaffy: v0.8.0 (master)

**What's actually happening?**
When clicking on the dashboard page link, all the items below it are marked as active and they are expanded.

**What should happen instead?**
Clicking on the dashboard link should only make the dashboard item active (white) while closing all the other menu items.

**Screenshots**
![Screen Shot 2020-05-30 at 16 37 28](https://user-images.githubusercontent.com/602354/83329778-0b7fb600-a294-11ea-96df-7d353cadef3b.png)

**Comment by areski** [comment]
You could not be more right, some crazy JS adding some style to the class. Fixed with https://github.com/aesmail/kaffy/pull/64
