### ISSUE TITLE
[FEATURE-REQUEST] MDI vs FontAwesome

### ISSUE THREAD

**Issue by areski** [aesmail/kaffy#74]
Kaffy was made using MDI icons, I would like to debate on the following and why are the cons against using FontAwesome. I feel that as we are using bootstrap and not material design, it would be more coherent to use Fontawesome too.
The choices of icons is also better to my opinions.

**Comment by aesmail** [comment]
I liked FA more tbh. I'm used to the FA icon names and memorized a lot of them by now which slows me down when working with MDI. I'm totally for this.
Would you be willing to tackle this?

**Comment by areski** [comment]
Feel the same, just wanted to make sure there was nothing forcing us to stick to MDI.
Cool, let's tackle this. 

I will take care of it!
