### ISSUE TITLE
Context with two words displayed as one word in sidebar

### ISSUE THREAD

**Issue by axelclark** [aesmail/kaffy#81]
A context with two words (e.g. `DraftPicks`) is displayed as `Draftpicks`.   It should be displayed as `Draft Picks` with the space.

A `DraftPick` resource with two words is displayed as `Draft Picks`.

Here are the two different functions in the `app.html.eex` template.

https://github.com/aesmail/kaffy/blob/79b7ee3286d52c92db4365c391553c6377202ca4/lib/kaffy_web/templates/layout/app.html.eex#L92

https://github.com/aesmail/kaffy/blob/79b7ee3286d52c92db4365c391553c6377202ca4/lib/kaffy_web/templates/layout/app.html.eex#L100

**Comment by aesmail** [comment]
This has been fixed in master.

**Comment by axelclark** [comment]
@aesmail, I'm using the master branch and it doesn't seem to be fixed for me (see `Draftpicks`, `Draftqueues`, and `Fantasyleagues`).
![image](https://user-images.githubusercontent.com/16856928/84654972-2120ec80-aede-11ea-837f-4720bab013b5.png)

**Comment by aesmail** [comment]
Just pushed another commit that should fix this.

**Comment by axelclark** [comment]
@aesmail good to go!  Thanks!!
