### ISSUE TITLE
[FEATURE-REQUEST] Show case project

### ISSUE THREAD

**Issue by areski** [aesmail/kaffy#86]
I think it would help if we had an other repo to show case kaffy, a bit like `https://github.com/areski/ex-chitchat`, this project is just for me to play with Kaffy.
It might be good to have your own, where we can show and try all the existing functionalities.
Ideally it should be what we show on the live demo.

Thoughts?

**Comment by aesmail** [comment]
Yes I agree. I've been meaning to create a repo for the live demo and add as many features as possible but have been lazy in this regard. Also, the current demo is extremely simple and doesn't show most of the features.

I think the project we eventually use should have a simple interface for the "normal" page and a "/admin" endpoint to control that. I'll upload the `bakery` project (current demo) today so you can take a look. Then we can decide how to proceed.

**Comment by areski** [comment]
Sounds good, Thanks!

**Comment by areski** [comment]
Any progress on that? I really think that could be very useful, so people could see the code used by the demo, but also see example of how to use some functionalities.

**Comment by aesmail** [comment]
I'll make a public repo for the current demo website today. Feel free to modify it as you wish.

**Comment by aesmail** [comment]
Finally this is done at https://github.com/aesmail/kaffy-demo

**Comment by areski** [comment]
I'm having some issues to get this working :face_with_head_bandage:

**Comment by aesmail** [comment]
You could actually rewrite most of it.
It’s not important how it’s done.
The important thing is that it works.
I think you’re having issues because maybe it’s using features that were experimental and never shipped I was playing with them.
If you want to replace the whole thing with your experimental project, be my guest.

I will just “git push” to gigalixir 😄

**Comment by areski** [comment]
My demo project is broken with the same error, I have opened a bug here with more detail https://github.com/aesmail/kaffy-demo/issues/1
It's certainly relate to the new `build_resources`, as it's working without it.
