### ISSUE TITLE
[FEATURE-REQUEST] Provide a way to customize the default query

### ISSUE THREAD

**Issue by zenbaku** [aesmail/kaffy#90]
**Describe the problem you're proposing to solve**

Hello, @aesmail! I'm currently working on a multi-tenant application and was looking for ways to build an admin panel to manage resources across tenants and came upon your project. It looks very good!

In my use case, I'm using [Triplex](https://github.com/ateliware/triplex) to manage multiple tenants using a tenant model and postgresql schemas. Each tenant maps to a postgresql schema and I'm using [Ecto query prefix](https://hexdocs.pm/ecto/Ecto.Query.html#module-query-prefix) on all my queries so they use the correct schema for each tenant.

Looking at Kaffy, (`Kaffy.ResourceQuery`) it seems there is not currently a way to define this prefix (or more Ecto options).

**Describe the solution you'd like**

A mechanism so I can hook into the query building and, using the current connection, modify the query.

**Describe alternatives you've considered**

Previously, I've used django for admin panels and it has a method `get_queryset` in which you can build your own query and the admin builds upon that (more info: https://docs.djangoproject.com/en/3.0/ref/contrib/admin/#django.contrib.admin.ModelAdmin.get_queryset). I think this is a good solution, however, it's designed around inheritance of classes and I don't know if Kaffy should do that.

Another, simpler solution for my use case would be to define a `get_prefix` on the resource and use that on `ResourceQuery` module. 

**Additional context**

I use DNS based routing, example:

- tenant1.app.domain
- tenant2.app.domain
- tenant3.app.domain

Tenants have separte schemas, so all queries use just one schema. I think I can manage doing something like `tenantX.app.domain/admin`, and, given the domain, customize the queries run on the admin.

**Comment by zenbaku** [comment]
Forgot to mention, I'd like to tackle this, but I think I will need some guidence on how to do it

**Comment by aesmail** [comment]
Hello @zenbaku 
This is a fantastic proposal. I appreciate the details you included in this issue.

You could definitely tackle this if you want. I'd be happy to provide some help and feedback.

Ok, I'm just thinking out loud here.
A `get_prefix` function could work, but it's very limited.
django's `get_queryset` might actually work nicely with Kaffy.
You might have an optional function in the resource admin, say `modify_query/2`, where you pass the `conn` and the `query` struct, modify the query when needed, then return a query struct back to Kaffy. This would give you total control on the query Kaffy will run.

Maybe it would be nice to easily/quickly differentiate between whether the query is for the index page or another page, whether it's for creating or updating a record, etc.

Another potential option is there could be optional callbacks like `before_list` and `before_show` to potentially manipulate the results. The `before_list` function might be enough, however, I'm thinking `before_show` could also be used to enforce access to individual records.

What do you think?

**Comment by zenbaku** [comment]
Hello @aesmail, thanks for such a quick reply!

I initially went to the callbacks section in the documentation in hope of seeing something like what you describe (`before_list`, `before_show`, etc), so I think that is a good solution as well.

I think that maybe `modify_query` could act as a "base" query builder, before it's decided whatever it would be a list or a show.

Having both `modify_query` and callbacks might confuse users as to what mechanisim should be used to customize the data being shown. It seems to me that callbacks are more oriented towards flow/access and that `modify_query`more towards data retrieval (even it it's prevented/denied as part of the flow).

Let me know what you think about these points and I can see how to implement these 😄

**Comment by aesmail** [comment]
I'm onboard with your points.
Go ahead 👍🏼

**Comment by aesmail** [comment]
Hey @zenbaku, sorry for not checking in it's been busy.
Any updates on this? Did you start or do you want me to start and you help along the way?
