### ISSUE TITLE
[BUG] Need for @conn in render_index

### ISSUE THREAD

**Issue by areski** [aesmail/kaffy#93]
It seems that I would need @conn in `render_index` to be able to render `static_url` or `static_path`
https://github.com/aesmail/kaffy/blob/custom-types/lib/kaffy/resource_schema.ex#L164

Any objections for me to pass @conn to `kaffy_field_value` so that we can then pass it to `render_index`

**Comment by aesmail** [comment]
Not at all, actually I'm surprised `conn` is not being passed to `render_index`.

**Comment by areski** [comment]
Closing this issue as it's fixed here now: https://github.com/aesmail/kaffy/pull/91/commits/4fefae9506557a3a57e68871f018ef6dcd68619d
