### ISSUE TITLE
[BUG] Getting field names given to change/put_change must be atoms when saving

### ISSUE THREAD

**Issue by joshuaswilcox** [aesmail/kaffy#94]
**Versions Used**
Kaffy: 0.8.0
Phoenix: 1.4.0
Elixir: 1.10.3

**What's actually happening?**
When i try to save in admin i get that error on all models

        @required_fields ~w(email password)a
        def create_changeset(model, params \\ :invalid) do
          model
          |> cast(params, @required_fields)
          |> unique_constraint(:email)
          |> validate_format(:email, ~r/@/)
          |> validate_length(:password, min: 5)
          |> hash_password
        end

**What should happen instead?**
I should save the model to the database

**Screenshots**
<img width="1560" alt="Screen Shot 2020-06-13 at 8 09 09 AM" src="https://user-images.githubusercontent.com/512078/84568415-6235c700-ad4d-11ea-845d-3753a37ee35d.png">

**Comment by joshuaswilcox** [comment]
Nevermind, this was an issue on my side, thanks for the great admin

**Comment by aesmail** [comment]
Ah! Good to know! I was actually trying to debug this since it looked like a major issue!
Glad it's working out for you 👍🏼

**Comment by joshuaswilcox** [comment]
I actually would expect that as `defp` means the method is only available internally to the model, not from an external source calling it

**Comment by aesmail** [comment]
@studyro digging deeper, I think the issue is not casting the changes before calling `Ecto.Changeset.change/2`.

This needs to be fixed.

**Comment by aesmail** [comment]
That was quicker than I expected.
@studyro you have 2 options now

- Have an explicit `changeset/2` function in your schema.
- Use the master branch where the issue you're facing should be fixed with the latest commit.

Note that there is one *known* issue currently with `many_to_many` fields which makes you still want to use your own changeset function if you have that defined in your schema.

**Comment by Kabie** [comment]
This issue also applys to `Kaffy.ResourceAdmin.update_changeset` and others.
@aesmail
