### ISSUE TITLE
[BUG] belongs_to association is blank in form

### ISSUE THREAD

**Issue by axelclark** [aesmail/kaffy#98]
**Versions Used**
Kaffy: 0.8.1
Phoenix: 1.5.3
Elixir: 1.10.3

**What's actually happening?**
In my [Ex338 project](https://github.com/axelclark/ex338), `fantasy_team` `belongs_to` association is blank in the form for `owners`.

EDIT: After further investigation, it looks like it uses `commish_notes` which is the first string alphabetically, but is blank for all of my seed fantasy teams.

```elixir
  schema "owners" do
    belongs_to(:fantasy_team, Ex338.FantasyTeams.FantasyTeam)
    belongs_to(:user, Ex338.Accounts.User)
    field(:rules, OwnerRulesEnum, default: "unaccepted")

    timestamps()
  end
```
```elixir
  schema "fantasy_teams" do
    field(:team_name, :string)
    field(:waiver_position, :integer)
    field(:winnings_adj, :float, default: 0.0)
    field(:dues_paid, :float, default: 0.0)
    field(:winnings_received, :float, default: 0.0)
    field(:max_flex_adj, :integer, default: 0)
    field(:commish_notes, :string)
    field(:autodraft_setting, FantasyTeamAutodraftSettingEnum, default: "on")
    field(:slot_results, {:array, :map}, virtual: true, default: [])
    field(:total_seconds_on_the_clock, :integer, virtual: true, default: 0)
    field(:avg_seconds_on_the_clock, :integer, virtual: true, default: 0)
    field(:total_draft_mins_adj, :integer, default: 0)
    field(:picks_selected, :integer, virtual: true, default: 0)
    field(:over_draft_time_limit?, :boolean, virtual: true, default: false)
  end
```

**What should happen instead?**
`sports_league` `belongs_to` association displays `abbrev` in the form for `fantasy_players`.

```elixir
  schema "fantasy_players" do
    field(:player_name, :string)
    belongs_to(:sports_league, Ex338.FantasyPlayers.SportsLeague)
  end
```
```elixir
  schema "sports_leagues" do
    field(:league_name, :string)
    field(:abbrev, :string)
    field(:hide_waivers, :boolean)
  end
```
**Screenshots**
![image](https://user-images.githubusercontent.com/16856928/84598538-7951e300-ae39-11ea-960e-df3d4a18227d.png)

Select options are blank, but the options are generated
![image](https://user-images.githubusercontent.com/16856928/84598977-9340f500-ae3c-11ea-836a-dfa7df945fad.png)

![image](https://user-images.githubusercontent.com/16856928/84598740-edd95180-ae3a-11ea-9817-0de33c883f28.png)

![image](https://user-images.githubusercontent.com/16856928/84599009-e61aac80-ae3c-11ea-9066-3fd678571e8d.png)

**Comment by axelclark** [comment]
After further investigation, I don't think this is a bug.  It is using the `commish_notes` field which is blank for all of my fantasy teams.  When I add a note, it shows up in the select.  However, I'd like to propose the same convention discussed in #97.

**Comment by axelclark** [comment]
My #99 pull request would close this issue as well since the form uses the same function.

**Comment by aesmail** [comment]
Perfect 👍🏼
